spring:
  application:
    name: CatapultGeneratorApplication
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tribal_wars
    username: 'tribal'
    password: 'password'
#  liquibase:
#    change-log: classpath:database/changelog/changelog-master.xml
#    drop-first: true
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    generate-ddl: true