spring:
  application:
    name: CatapultGeneratorApplication
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tribal_wars
    username: 'tribal'
    password: 'password'
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    generate-ddl: true